name: tests

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        python:
        - version: 3.6
          toxenv: py36
        - version: 3.7
          toxenv: py37
        - version: 3.8
          toxenv: py38

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python.version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install -r requirements.txt

    - name: Test with tox ${{ matrix.python.toxenv }}
      env:
        TOXENV: ${{ matrix.python.toxenv }}
      run: tox

    - name: Report coverage
      if: matrix.python.version == '3.8'
      run: |
        coverage combine
        coverage report
        coverage xml

    - name: Upload coverage to Codecov  
      if: matrix.python.version == '3.8'
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: GitHub
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Docs
      run: |
        make -f Makefile.sphinx html
