name: tests

on:
- push
- pull_request

jobs:
  test_minimal_ubuntu:
    strategy:
      fail-fast: false
      max-parallel: 3

    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.version }}

    - name: apt update
      run: apt update

    - name: install python
      run: apt install -y python3.8

    - name: install pip
      run: apt install -y python3-pip

    - name: intall requirements.txt
      run: pip3 install -r requirements.txt

    - name: install from setup.py
      run: python3 setup.py install

  test:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python:
        - version: 3.6
          toxenv: py36
        - version: 3.7
          toxenv: py37
        - version: 3.8
          toxenv: py38
        - version: 3.9
          toxenv: py39
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install -r requirements.txt

    - name: Test with tox ${{ matrix.python.toxenv }}
      env:
        TOXENV: ${{ matrix.python.toxenv }}
      run: tox

    - name: Report coverage
      if: matrix.python.version == '3.8'
      run: |
        coverage combine
        coverage report
        coverage xml

    - name: Upload coverage to Codecov  
      if: matrix.python.version == '3.8'
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: GitHub
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python.version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Docs
      run: |
        make -f Makefile.sphinx html
